### ISSUE TITLE
add cpu_steal graph

### ISSUE THREAD

**Issue by tedder** [tedder/helium_miner_grafana_dashboard#4]
@kellybyrd this one's for you. it'll be valuable for at least a large minority of users.

**Comment by kellybyrd** [comment]
I'll take it! Go ahead and assign it to me. 

 I can see this going a few ways, what's your opinion?
- Graph all components of CPU (io_wait, user, system, steal) as individual stacked lines
- Graph just steal, all the rest as one chunk

The first one covers more situations, and because it's stacked, users that only care about used vs free can quickly look. Actually both would work that way.

**Comment by tedder** [comment]
I like "graph all the things", my only concern is if the steal is such a small portion (1%) that it's hard to see. Feel free to do whatever you want.
